#!/bin/bash
set -e

case "$1" in
    remove|deconfigure)
        # Stop service (handled by debhelper)  
        deb-systemd-invoke stop timelapse.service >/dev/null || true
        
        # Disable Apache site
        a2dissite timelapse-apache >/dev/null 2>&1 || true
        deb-systemd-helper restart apache2 >/dev/null 2>&1 || true
        ;;
    upgrade)
        # Don't stop service during upgrade
        ;;
    *)
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'timelapse.service' >/dev/null || true
fi
# End automatically added section


exit 0
